-- Make rail operation optional fields nullable and add Rake ID against FNR No.

IF COL_LENGTH('dbo.Loading_Stage', 'Rake_ID_Against_FNR_No') IS NULL
BEGIN
    ALTER TABLE [dbo].[Loading_Stage]
    ADD [Rake_ID_Against_FNR_No] NVARCHAR(50) NULL;
END;
GO

ALTER TABLE [dbo].[RAKE_MASTER] ALTER COLUMN [Operator] NVARCHAR(50) NULL;
ALTER TABLE [dbo].[RAKE_MASTER] ALTER COLUMN [Max_Composition] INT NULL;
ALTER TABLE [dbo].[RAKE_MASTER] ALTER COLUMN [Purchase_Date] DATE NULL;
ALTER TABLE [dbo].[RAKE_MASTER] ALTER COLUMN [Comm_Date] DATE NULL;
ALTER TABLE [dbo].[RAKE_MASTER] ALTER COLUMN [ROH_Months] INT NULL;
ALTER TABLE [dbo].[RAKE_MASTER] ALTER COLUMN [POH_Months] INT NULL;
ALTER TABLE [dbo].[RAKE_MASTER] ALTER COLUMN [Lease_From] DATE NULL;
ALTER TABLE [dbo].[RAKE_MASTER] ALTER COLUMN [Lease_To] DATE NULL;
ALTER TABLE [dbo].[RAKE_MASTER] ALTER COLUMN [Lease_Loc] NVARCHAR(20) NULL;
ALTER TABLE [dbo].[RAKE_MASTER] ALTER COLUMN [Handover_At] NVARCHAR(20) NULL;
ALTER TABLE [dbo].[RAKE_MASTER] ALTER COLUMN [Exam_Date] DATE NULL;
ALTER TABLE [dbo].[RAKE_MASTER] ALTER COLUMN [Base_Depot] NVARCHAR(20) NULL;
GO

ALTER TABLE [dbo].[RAKE_PLANNING] ALTER COLUMN [Base_Depot] NVARCHAR(20) NULL;
ALTER TABLE [dbo].[RAKE_PLANNING] ALTER COLUMN [Rake_Operator] NVARCHAR(50) NULL;
ALTER TABLE [dbo].[RAKE_PLANNING] ALTER COLUMN [Haulage_Paid_By] NVARCHAR(20) NULL;
ALTER TABLE [dbo].[RAKE_PLANNING] ALTER COLUMN [Trip_No] NVARCHAR(20) NULL;
ALTER TABLE [dbo].[RAKE_PLANNING] ALTER COLUMN [Plan_Type] NVARCHAR(20) NULL;
ALTER TABLE [dbo].[RAKE_PLANNING] ALTER COLUMN [Device_ID] NVARCHAR(50) NULL;
ALTER TABLE [dbo].[RAKE_PLANNING] ALTER COLUMN [Route] NVARCHAR(20) NULL;
GO
